<a href="https://colab.research.google.com/github/Enock-Yegon/Introduction-to-Python/blob/main/pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv("/content/used_cars_data.csv")
df.head()

,S.No.,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,New_Price,Price
0,0,Maruti Wagon R LXI CNG,Mumbai,2010,72000,CNG,Manual,First,26.6 km/kg,998 CC,58.16 bhp,5.0,NaN,1.75
1,1,Hyundai Creta 1.6 CRDi SX Option,Pune,2015,41000,Diesel,Manual,First,19.67 kmpl,1582 CC,126.2 bhp,5.0,NaN,12.50
2,2,Honda Jazz V,Chennai,2011,46000,Petrol,Manual,First,18.2 kmpl,1199 CC,88.7 bhp,5.0,8.61 Lakh,4.50
3,3,Maruti Ertiga VDI,Chennai,2012,87000,Diesel,Manual,First,20.77 kmpl,1248 CC,88.76 bhp,7.0,NaN,6.00
4,4,Audi A4 New 2.0 TDI Multitronic,Coimbatore,2013,40670,Diesel,Automatic,Second,15.2 kmpl,1968 CC,140.8 bhp,5.0,NaN,17.74

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7253 entries, 0 to 7252
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   S.No.              7253 non-null   int64
 1   Name               7253 non-null   object
 2   Location           7253 non-null   object
 3   Year               7253 non-null   int64
 4   Kilometers_Driven  7253 non-null   int64
 5   Fuel_Type          7253 non-null   object
 6   Transmission       7253 non-null   object
 7   Owner_Type         7253 non-null   object
 8   Mileage            7251 non-null   object
 9   Engine             7207 non-null   object
 10  Power              7207 non-null   object
 11  Seats              7200 non-null   float64
 12  New_Price          1006 non-null   object
 13  Price              6019 non-null   float64
dtypes: float64(2), int64(3), object(9)
memory usage: 793.4+ KB

In [ ]:
df["Kilometers_Driven"] = df["Kilometers_Driven"].astype(float)
df["Location"] = df["Location"].astype("category")
df

,S.No.,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,New_Price,Price
0,0,Maruti Wagon R LXI CNG,Mumbai,2010,72000.0,CNG,Manual,First,26.6 km/kg,998 CC,58.16 bhp,5.0,NaN,1.75
1,1,Hyundai Creta 1.6 CRDi SX Option,Pune,2015,41000.0,Diesel,Manual,First,19.67 kmpl,1582 CC,126.2 bhp,5.0,NaN,12.50
2,2,Honda Jazz V,Chennai,2011,46000.0,Petrol,Manual,First,18.2 kmpl,1199 CC,88.7 bhp,5.0,8.61 Lakh,4.50
3,3,Maruti Ertiga VDI,Chennai,2012,87000.0,Diesel,Manual,First,20.77 kmpl,1248 CC,88.76 bhp,7.0,NaN,6.00
4,4,Audi A4 New 2.0 TDI Multitronic,Coimbatore,2013,40670.0,Diesel,Automatic,Second,15.2 kmpl,1968 CC,140.8 bhp,5.0,NaN,17.74
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7248,7248,Volkswagen Vento Diesel Trendline,Hyderabad,2011,89411.0,Diesel,Manual,First,20.54 kmpl,1598 CC,103.6 bhp,5.0,NaN,NaN
7249,7249,Volkswagen Polo GT TSI,Mumbai,2015,59000.0,Petrol,Automatic,First,17.21 kmpl,1197 CC,103.6 bhp,5.0,NaN,NaN
7250,7250,Nissan Micra Diesel XV,Kolkata,2012,28000.0,Diesel,Manual,First,23.08 kmpl,1461 CC,63.1 bhp,5.0,NaN,NaN
7251,7251,Volkswagen Polo GT TSI,Pune,2013,52262.0,Petrol,Automatic,Third,17.2 kmpl,1197 CC,103.6 bhp,5.0,NaN,NaN
7252,7252,Mercedes-Benz E-Class 2009-2013 E 220 CDI Avan...,Kochi,2014,72443.0,Diesel,Automatic,First,10.0 kmpl,2148 CC,170 bhp,5.0,NaN,NaN

In [ ]:
df["Location"].dtype

CategoricalDtype(categories=['Ahmedabad', 'Bangalore', 'Chennai', 'Coimbatore', 'Delhi',
                  'Hyderabad', 'Jaipur', 'Kochi', 'Kolkata', 'Mumbai', 'Pune'],
, ordered=False, categories_dtype=object)

In [ ]:
mumbai_cars_df = df[df["Location"] == "Mumbai"]
mumbai_cars_df["Kilometers_Driven"] * 1.16

0        83520.00
7        41760.00
22       64942.60
25       60227.20
29      303920.00
          ...
7185     36299.88
7218      4408.00
7229     78300.00
7232      6960.00
7249     68440.00
Name: Kilometers_Driven, Length: 949, dtype: float64

In [ ]:
df.memory_usage(deep=True)

Index                   132
S.No.                 58024
Name                 545118
Location               8169
Year                  58024
Kilometers_Driven     58024
Fuel_Type            398697
Transmission         405062
Owner_Type           392922
Mileage              423501
Engine               404348
Power                411805
Seats                 58024
New_Price            258674
Price                 58024
dtype: int64

In [ ]:
s = pd.Series(["250","100","N/A","400"])
pd.to_numeric(s, errors="coerce")

0    250.0
1    100.0
2      NaN
3    400.0
dtype: float64

In [ ]:
df.describe()

             S.No.         Year  Kilometers_Driven        Seats        Price
count  7253.000000  7253.000000       7.253000e+03  7200.000000  6019.000000
mean   3626.000000  2013.365366       5.869906e+04     5.279722     9.479468
std    2093.905084     3.254421       8.442772e+04     0.811660    11.187917
min       0.000000  1996.000000       1.710000e+02     0.000000     0.440000
25%    1813.000000  2011.000000       3.400000e+04     5.000000     3.500000
50%    3626.000000  2014.000000       5.341600e+04     5.000000     5.640000
75%    5439.000000  2016.000000       7.300000e+04     5.000000     9.950000
max    7252.000000  2019.000000       6.500000e+06    10.000000   160.000000

In [ ]:
df.columns

Index(['S.No.', 'Name', 'Location', 'Year', 'Kilometers_Driven', 'Fuel_Type',
       'Transmission', 'Owner_Type', 'Mileage', 'Engine', 'Power', 'Seats',
       'New_Price', 'Price'],
      dtype='object')

In [ ]:
df.dtypes

S.No.                  int64
Name                  object
Location              object
Year                   int64
Kilometers_Driven      int64
Fuel_Type             object
Transmission          object
Owner_Type            object
Mileage               object
Engine                object
Power                 object
Seats                float64
New_Price             object
Price                float64
dtype: object

In [ ]:
df.index

RangeIndex(start=0, stop=7253, step=1)

In [ ]:
df.size

101542

In [ ]:
df["Location"]
df[["Location", "Seats","Engine"]]

        Location  Seats   Engine
0         Mumbai    5.0   998 CC
1           Pune    5.0  1582 CC
2        Chennai    5.0  1199 CC
3        Chennai    7.0  1248 CC
4     Coimbatore    5.0  1968 CC
...          ...    ...      ...
7248   Hyderabad    5.0  1598 CC
7249      Mumbai    5.0  1197 CC
7250     Kolkata    5.0  1461 CC
7251        Pune    5.0  1197 CC
7252       Kochi    5.0  2148 CC

[7253 rows x 3 columns]

In [ ]:
df["Location"] == "Mumbai"

0        True
1       False
2       False
3       False
4       False
        ...
7248    False
7249     True
7250    False
7251    False
7252    False
Name: Location, Length: 7253, dtype: bool

In [ ]:
import pandas as pd
df = pd.read_csv("/content/used_cars_data.csv")

is_Mumbai = df["Location"] == "Mumbai"
is_Kilometers_Driven = df["Kilometers_Driven"] > 60000
df[is_Mumbai | is_Kilometers_Driven]

,S.No.,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,New_Price,Price
0,0,Maruti Wagon R LXI CNG,Mumbai,2010,72000,CNG,Manual,First,26.6 km/kg,998 CC,58.16 bhp,5.0,NaN,1.75
3,3,Maruti Ertiga VDI,Chennai,2012,87000,Diesel,Manual,First,20.77 kmpl,1248 CC,88.76 bhp,7.0,NaN,6.00
5,5,Hyundai EON LPG Era Plus Option,Hyderabad,2012,75000,LPG,Manual,First,21.1 km/kg,814 CC,55.2 bhp,5.0,NaN,2.35
6,6,Nissan Micra Diesel XV,Jaipur,2013,86999,Diesel,Manual,First,23.08 kmpl,1461 CC,63.1 bhp,5.0,NaN,3.50
7,7,Toyota Innova Crysta 2.8 GX AT 8S,Mumbai,2016,36000,Diesel,Automatic,First,11.36 kmpl,2755 CC,171.5 bhp,8.0,21 Lakh,17.50
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7241,7241,BMW 5 Series 525d Sedan,Delhi,2012,80000,Diesel,Automatic,First,16.73 kmpl,2993 CC,218 bhp,5.0,NaN,NaN
7243,7243,Renault Duster 85PS Diesel RxL,Chennai,2015,70000,Diesel,Manual,First,19.87 kmpl,1461 CC,83.8 bhp,5.0,NaN,NaN
7248,7248,Volkswagen Vento Diesel Trendline,Hyderabad,2011,89411,Diesel,Manual,First,20.54 kmpl,1598 CC,103.6 bhp,5.0,NaN,NaN
7249,7249,Volkswagen Polo GT TSI,Mumbai,2015,59000,Petrol,Automatic,First,17.21 kmpl,1197 CC,103.6 bhp,5.0,NaN,NaN
7252,7252,Mercedes-Benz E-Class 2009-2013 E 220 CDI Avan...,Kochi,2014,72443,Diesel,Automatic,First,10.0 kmpl,2148 CC,170 bhp,5.0,NaN,NaN

In [ ]:
df[df["Kilometers_Driven"] > 60000]

,S.No.,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,New_Price,Price
0,0,Maruti Wagon R LXI CNG,Mumbai,2010,72000,CNG,Manual,First,26.6 km/kg,998 CC,58.16 bhp,5.0,NaN,1.75
3,3,Maruti Ertiga VDI,Chennai,2012,87000,Diesel,Manual,First,20.77 kmpl,1248 CC,88.76 bhp,7.0,NaN,6.00
5,5,Hyundai EON LPG Era Plus Option,Hyderabad,2012,75000,LPG,Manual,First,21.1 km/kg,814 CC,55.2 bhp,5.0,NaN,2.35
6,6,Nissan Micra Diesel XV,Jaipur,2013,86999,Diesel,Manual,First,23.08 kmpl,1461 CC,63.1 bhp,5.0,NaN,3.50
8,8,Volkswagen Vento Diesel Comfortline,Pune,2013,64430,Diesel,Manual,First,20.54 kmpl,1598 CC,103.6 bhp,5.0,NaN,5.20
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7238,7238,Audi A4 2.0 TDI,Hyderabad,2011,64000,Diesel,Automatic,First,16.55 kmpl,1968 CC,147.51 bhp,5.0,NaN,NaN
7241,7241,BMW 5 Series 525d Sedan,Delhi,2012,80000,Diesel,Automatic,First,16.73 kmpl,2993 CC,218 bhp,5.0,NaN,NaN
7243,7243,Renault Duster 85PS Diesel RxL,Chennai,2015,70000,Diesel,Manual,First,19.87 kmpl,1461 CC,83.8 bhp,5.0,NaN,NaN
7248,7248,Volkswagen Vento Diesel Trendline,Hyderabad,2011,89411,Diesel,Manual,First,20.54 kmpl,1598 CC,103.6 bhp,5.0,NaN,NaN
7252,7252,Mercedes-Benz E-Class 2009-2013 E 220 CDI Avan...,Kochi,2014,72443,Diesel,Automatic,First,10.0 kmpl,2148 CC,170 bhp,5.0,NaN,NaN

In [ ]:
data = {
    "name": ["Alice", "Bob", "Charlie", "Diana", "Enock"],
    "age": [25, 30, 35, 40, 45],
    "gender": ["F", "M", "M", "F", "M"]
}
df = pd.DataFrame(data)
df.columns = df.columns.str.capitalize()
df.head()

      Name  Age Gender
0    Alice   25      F
1      Bob   30      M
2  Charlie   35      M
3    Diana   40      F
4    Enock   45      M

In [ ]:
import pandas as pd

# Re-initialize df as it was overwritten to a tuple
data = {
    "name": ["Alice", "Bob", "Charlie", "Diana", "Enock"],
    "age": [25, 30, 35, 40, 45],
    "gender": ["F", "M", "M", "F", "M"]
}
df = pd.DataFrame(data)
df.columns = df.columns.str.capitalize()

Male = df["Gender"] == "M"
Age = df["Age"] >= 30
df[Male & Age]

      Name  Age Gender
1      Bob   30      M
2  Charlie   35      M
4    Enock   45      M

In [ ]:
row_count = len(Male)
print(row_count)

5

In [ ]:
df["Location"] == "Mumbai"
df[df["Location"] == "Mumbai"]

,S.No.,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,New_Price,Price
0,0,Maruti Wagon R LXI CNG,Mumbai,2010,72000,CNG,Manual,First,26.6 km/kg,998 CC,58.16 bhp,5.0,NaN,1.75
7,7,Toyota Innova Crysta 2.8 GX AT 8S,Mumbai,2016,36000,Diesel,Automatic,First,11.36 kmpl,2755 CC,171.5 bhp,8.0,21 Lakh,17.50
22,22,Audi A6 2011-2015 35 TFSI Technology,Mumbai,2015,55985,Petrol,Automatic,First,13.53 kmpl,1984 CC,177.01 bhp,5.0,NaN,23.50
25,25,Honda City Corporate Edition,Mumbai,2012,51920,Petrol,Manual,First,16.8 kmpl,1497 CC,116.3 bhp,5.0,NaN,4.25
29,29,Toyota Innova 2.5 V Diesel 7-seater,Mumbai,2007,262000,Diesel,Manual,Fourth & Above,12.8 kmpl,2494 CC,102 bhp,7.0,NaN,4.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7185,7185,Hyundai i20 Asta Option 1.2,Mumbai,2015,31293,Petrol,Manual,First,18.6 kmpl,1197 CC,81.83 bhp,5.0,NaN,NaN
7218,7218,Maruti Vitara Brezza ZDi Plus AMT,Mumbai,2018,3800,Diesel,Automatic,First,24.3 kmpl,1248 CC,88.5 bhp,5.0,12.46 Lakh,NaN
7229,7229,Volkswagen Vento Petrol Highline AT,Mumbai,2011,67500,Petrol,Automatic,Second,14.4 kmpl,1598 CC,103.6 bhp,5.0,NaN,NaN
7232,7232,Jeep Compass 1.4 Sport,Mumbai,2018,6000,Petrol,Manual,First,16.0 kmpl,1368 CC,160 bhp,5.0,18.16 Lakh,NaN
7249,7249,Volkswagen Polo GT TSI,Mumbai,2015,59000,Petrol,Automatic,First,17.21 kmpl,1197 CC,103.6 bhp,5.0,NaN,NaN

In [ ]:
a = pd.Series([10,25,30,45])
a>20

0    False
1     True
2     True
3     True
dtype: bool

In [ ]:
df.loc[2, "Location"]

'Chennai'

## Intro to Pandas: Data Structures & Basics

### Overview
**Pandas** is an open-source library built on top of NumPy. It introduces two primary data structures that make handling tabular data fast and intuitive:

1. **Series**: A 1D labeled array (like a single column in Excel).
2. **DataFrame**: A 2D labeled data structure with rows and columns (like an entire Excel sheet or SQL table).

---

### Core Data Structures
| Structure | Dimensions | Description |
| :--- | :--- | :--- |
| **Series** | 1D | Single column of homogenous or mixed data with an index. |
| **DataFrame** | 2D | Tabular spreadsheet with row indices and column labels. |

---

### Key Learning Objectives
* Creating DataFrames from dictionaries.
* Inspecting datasets (`head()`, `info()`, `describe()`).
* Selecting specific columns and filtering rows with conditions.

In [ ]:
df = pd.read_csv("/content/used_cars_data.csv")
df.head()
df [df["Location"] == "Mumbai"]
df [ ~ df]

In [ ]:
import pandas as pd

# 1. Create a simple dataset using a Python dictionary
data = {
    "Name": ["Alice", "Bob", "Charlie", "Diana", "Enock"],
    "Department": ["HR", "IT", "Data Science", "IT", "Data Science"],
    "Score": [88, 42, 95, 68, 91],
    "Passed": [True, False, True, True, True],
}

# 2. Convert dictionary to a Pandas DataFrame
df = pd.DataFrame(data)

# 3. View the first few rows
print("=== DATAFRAME OVERVIEW ===")
print(df)

# 4. Quick inspection tools
print("\n=== SUMMARY INFO ===")
df.info()

print("\n=== STATISTICAL SUMMARY ===")
print(df.describe())

# 5. Filtering rows (e.g., Score >= 70)
print("\n=== HIGH SCORERS (Score >= 70) ===")
high_scorers = df[df["Score"] >= 70]
print(high_scorers)

=== DATAFRAME OVERVIEW ===
      Name    Department  Score  Passed
0    Alice            HR     88    True
1      Bob            IT     42   False
2  Charlie  Data Science     95    True
3    Diana            IT     68    True
4    Enock  Data Science     91    True

=== SUMMARY INFO ===
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        5 non-null      object
 1   Department  5 non-null      object
 2   Score       5 non-null      int64
 3   Passed      5 non-null      bool
dtypes: bool(1), int64(1), object(2)
memory usage: 257.0+ bytes

=== STATISTICAL SUMMARY ===
           Score
count   5.000000
mean   76.800000
std    22.061278
min    42.000000
25%    68.000000
50%    88.000000
75%    91.000000
max    95.000000

=== HIGH SCORERS (Score >= 70) ===
      Name    Department  Score  Passed
0    Alice            HR     88    True
2  Charlie  Data Science     95    True
4    Enock  Data Science     91    True

In [ ]:
df["Department"] == "Data Science"
df[df["Department"] == "Data Science"]

      Name    Department  Score  Passed
2  Charlie  Data Science     95    True
4    Enock  Data Science     91    True

In [ ]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All"
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [ ]:
df = pd.read_csv('/content/laptopData.csv')
df.head()

,Unnamed: 0,Company,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price
0,0.0,Apple,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8GB,128GB SSD,Intel Iris Plus Graphics 640,macOS,1.37kg,71378.6832
1,1.0,Apple,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8GB,128GB Flash Storage,Intel HD Graphics 6000,macOS,1.34kg,47895.5232
2,2.0,HP,Notebook,15.6,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8GB,256GB SSD,Intel HD Graphics 620,No OS,1.86kg,30636.0000
3,3.0,Apple,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel Core i7 2.7GHz,16GB,512GB SSD,AMD Radeon Pro 455,macOS,1.83kg,135195.3360
4,4.0,Apple,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 3.1GHz,8GB,256GB SSD,Intel Iris Plus Graphics 650,macOS,1.37kg,96095.8080

In [ ]:
df.drop('Unnamed: 0', axis=1, inplace=True)
df

KeyError: "['Unnamed: 0'] not found in axis"

In [ ]:
tem_df = df.copy()
tem_df.head(5)

,Company,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price
0,Apple,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8GB,128GB SSD,Intel Iris Plus Graphics 640,macOS,1.37kg,71378.6832
1,Apple,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8GB,128GB Flash Storage,Intel HD Graphics 6000,macOS,1.34kg,47895.5232
2,HP,Notebook,15.6,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8GB,256GB SSD,Intel HD Graphics 620,No OS,1.86kg,30636.0000
3,Apple,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel Core i7 2.7GHz,16GB,512GB SSD,AMD Radeon Pro 455,macOS,1.83kg,135195.3360
4,Apple,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 3.1GHz,8GB,256GB SSD,Intel Iris Plus Graphics 650,macOS,1.37kg,96095.8080

In [ ]:
tem_df.sample(5)

,Company,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price
328,HP,Ultrabook,12.5,Full HD 1920x1080,Intel Core i7 7500U 2.7GHz,8GB,256GB SSD,Intel HD Graphics 620,Windows 10,1.26kg,71128.80
993,Lenovo,Notebook,15.6,Full HD 1920x1080,Intel Core i5 6200U 2.3GHz,8GB,256GB SSD,Intel HD Graphics 520,Windows 10,2.3kg,71874.72
1050,Lenovo,Notebook,14,IPS Panel 2560x1440,Intel Core i7 6600U 2.6GHz,16GB,256GB SSD,Intel HD Graphics 520,Windows 7,1.1kg,139593.60
863,Lenovo,Gaming,15.6,IPS Panel Full HD 1920x1080,Intel Core i5 7300HQ 2.5GHz,8GB,1TB HDD,Nvidia GeForce GTX 1050,No OS,2.5kg,54185.76
1103,HP,Workstation,17.3,IPS Panel Full HD 1920x1080,Intel Core i7 6700HQ 2.6GHz,8GB,1TB HDD,AMD FirePro W6150M,Windows 7,3.0kg,154458.72

In [ ]:
tem_df.duplicated().sum()
df

,Company,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price
0,Apple,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8GB,128GB SSD,Intel Iris Plus Graphics 640,macOS,1.37kg,71378.6832
1,Apple,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8GB,128GB Flash Storage,Intel HD Graphics 6000,macOS,1.34kg,47895.5232
2,HP,Notebook,15.6,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8GB,256GB SSD,Intel HD Graphics 620,No OS,1.86kg,30636.0000
3,Apple,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel Core i7 2.7GHz,16GB,512GB SSD,AMD Radeon Pro 455,macOS,1.83kg,135195.3360
4,Apple,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 3.1GHz,8GB,256GB SSD,Intel Iris Plus Graphics 650,macOS,1.37kg,96095.8080
...,...,...,...,...,...,...,...,...,...,...,...
1298,Lenovo,2 in 1 Convertible,14,IPS Panel Full HD / Touchscreen 1920x1080,Intel Core i7 6500U 2.5GHz,4GB,128GB SSD,Intel HD Graphics 520,Windows 10,1.8kg,33992.6400
1299,Lenovo,2 in 1 Convertible,13.3,IPS Panel Quad HD+ / Touchscreen 3200x1800,Intel Core i7 6500U 2.5GHz,16GB,512GB SSD,Intel HD Graphics 520,Windows 10,1.3kg,79866.7200
1300,Lenovo,Notebook,14,1366x768,Intel Celeron Dual Core N3050 1.6GHz,2GB,64GB Flash Storage,Intel HD Graphics,Windows 10,1.5kg,12201.1200
1301,HP,Notebook,15.6,1366x768,Intel Core i7 6500U 2.5GHz,6GB,1TB HDD,AMD Radeon R5 M330,Windows 10,2.19kg,40705.9200
1302,Asus,Notebook,15.6,1366x768,Intel Celeron Dual Core N3050 1.6GHz,4GB,500GB HDD,Intel HD Graphics,Windows 10,2.2kg,19660.3200